# This workflow is centrally managed in https://github.com/asyncapi/.github/
# Don't make changes to this file in this repo as they will be overwritten with changes made to the same file in above mentioned repo

# This workflow will run on every push to the repository or comment with /update or /u. And will create merge-commits for all PRs to respective branches.
# This also works with forks, not only with branches in the same repository/organization.
# Currently, does not work with forks in different organizations.

# This workflow will be distributed to all repositories in the AsyncAPI organization.

name: Autoupdate PR branches

on:
  push:
    branches-ignore:  
      - 'version-bump/**'
      - 'dependabot/**'
      - 'bot/**'
      - 'all-contributors/**'

  issue_comment: 
    types: [created]

jobs:
  autoupdate-fork:
    if: > 
      startsWith(github.repository, 'asyncapi/') &&
      (
        github.event_name == 'push' ||
        (
          github.event_name == 'issue_comment' &&
          github.event.issue.pull_request != null &&
          (
            contains(github.event.comment.body, '/update') ||
            contains(github.event.comment.body, '/u')
          )
        )
      )
    runs-on: ubuntu-latest
    steps:
      - name: Autoupdate PR branches
        uses: Shurtu-gal/autoupdate-fork-action@a5019320a0462993ded9bbe6c04fb1c6684d67c7
        with:
          github_token: ${{ secrets.GH_TOKEN || secrets.GITHUB_TOKEN }}
          # The label to see on push event. By default, on issue_comment event there will be no PR_FILTER
          pr_filter: 'labelled'
          pr_label: 'autoupdate'
          merge_fail_action: 'comment'
          ignore_conflicts: true
